#!/bin/bash
set -euo pipefail

APP_NAME="Liuyu.app"
BUNDLE_DIR="build/${APP_NAME}"

# --- Asset Processing ---
if [ -f "asset/menu.jpg" ]; then
    echo "Processing menu icon..."
    python3 scripts/process_icon.py "asset/menu.jpg" "Sources/LiuyuLib/Resources"
fi

if [ -f "asset/icon.png" ]; then
    echo "Processing app icon..."
    python3 scripts/process_app_icon.py "asset/icon.png" "Sources/LiuyuLib/Resources/AppIcon.icns"
fi

# --- Build ---

# Detect architecture for build path
ARCH=$(uname -m)
if [ "$ARCH" == "x86_64" ]; then
    BUILD_ARCH="x86_64-apple-macosx"
else
    BUILD_ARCH="arm64-apple-macosx"
fi

echo "Building release with Swift Package Manager..."
# Use --disable-sandbox to avoid permission issues in some environments
swift build --disable-sandbox -c release

echo "Creating app bundle structure..."
rm -rf "build/${APP_NAME}"
mkdir -p "${BUNDLE_DIR}/Contents/MacOS"
mkdir -p "${BUNDLE_DIR}/Contents/Resources"

# Path to built binary
BINARY_PATH=".build/${BUILD_ARCH}/release/Liuyu"

if [ -f "${BINARY_PATH}" ]; then
    echo "Copying binary..."
    cp "${BINARY_PATH}" "${BUNDLE_DIR}/Contents/MacOS/"
else
    echo "Error: Binary not found at ${BINARY_PATH}"
    exit 1
fi

echo "Copying resources..."
# Essential resources
cp "Sources/LiuyuLib/Resources/Info.plist" "${BUNDLE_DIR}/Contents/"
cp "Sources/LiuyuLib/Resources/AppIcon.icns" "${BUNDLE_DIR}/Contents/Resources/"

# Manually copy menu icons for legacy access via Bundle.main
cp "Sources/LiuyuLib/Resources/MenuIcon_18.png" "${BUNDLE_DIR}/Contents/Resources/"
cp "Sources/LiuyuLib/Resources/MenuIcon_18@2x.png" "${BUNDLE_DIR}/Contents/Resources/"

# Copy all resource bundles generated by SPM (e.g. Liuyu_LiuyuLib.bundle, LucideIcons_LucideIcons.bundle)
# Find bundles in the release directory
find ".build/${BUILD_ARCH}/release" -maxdepth 1 -name "*.bundle" -type d | while read bundle; do
    echo "Copying resource bundle: $(basename "$bundle")"
    cp -R "$bundle" "${BUNDLE_DIR}/Contents/Resources/"
done

echo "Signing app bundle..."
ENTITLEMENTS="Sources/LiuyuLib/Resources/Liuyu.entitlements"
BUNDLE_ID="com.liuyu.app"

sign_app() {
    local identity="$1"
    codesign --force --sign "${identity}" --entitlements "${ENTITLEMENTS}" --identifier "${BUNDLE_ID}" "${BUNDLE_DIR}"
}

# Check for "Liuyu Dev" certificate, but fall back if the signed app does not verify.
if security find-identity -v -p codesigning | grep -q "Liuyu Dev"; then
    if sign_app "Liuyu Dev" && codesign --verify --deep --strict --verbose=2 "${BUNDLE_DIR}"; then
        echo "Signed with Liuyu Dev"
    else
        echo "Warning: Liuyu Dev signing did not verify; falling back to ad-hoc signing"
        sign_app "-"
    fi
else
    echo "Note: Using ad-hoc signing (no 'Liuyu Dev' certificate found)"
    sign_app "-"
fi

codesign --verify --deep --strict --verbose=2 "${BUNDLE_DIR}"

echo "App bundle created at build/${APP_NAME}"
echo "Run with: open build/${APP_NAME}"
